pragma Singleton
import QtQuick

QtObject {
    // This data is auto-generated by update-sddm-backgrounds-cache
    // DO NOT EDIT THIS FILE MANUALLY - it will be overwritten
    readonly property string embeddedCacheData: ""
    
    property var userBackgrounds: ({})
    property bool cacheLoaded: false
    
    Component.onCompleted: {
        loadEmbeddedCache()
    }
    
    function loadEmbeddedCache() {
        if (embeddedCacheData.length === 0) {
            return
        }
        
        try {
            var data = JSON.parse(embeddedCacheData)
            for (var user in data) {
                userBackgrounds[user] = data[user]
            }
            cacheLoaded = true
        } catch (e) {
            console.error("AccountsService: Failed to parse cache data:", e)
        }
    }
    
    function getUserBackground(username) {
        if (!username || username.length === 0) {
            return ""
        }
        
        if (userBackgrounds.hasOwnProperty(username)) {
            return userBackgrounds[username]
        }
        
        return ""
    }
}
